local W,M,L,V = unpack(select(2,...))
if not V.common.popup then return end
local UnitPopupMenus = UnitPopupMenus

UnitPopupMenus["SELF"] = {
	"PVP_FLAG", 
	"LOOT_METHOD", 
	"LOOT_THRESHOLD",
	"OPT_OUT_LOOT_TITLE",
	"LOOT_PROMOTE",
	"CONVERT_TO_RAID",
	"CONVERT_TO_PARTY",
	"DUNGEON_DIFFICULTY",
	"RAID_DIFFICULTY",
	"RESET_INSTANCES",
	"RAID_TARGET_ICON",
	"SELECT_ROLE",
	"LEAVE",
	"CANCEL",}
	
UnitPopupMenus["PET"] = {
	"PET_PAPERDOLL", 
	"PET_RENAME", 
	"PET_ABANDON", 
	"PET_DISMISS", 
	"CANCEL",}
	
UnitPopupMenus["PARTY"] = {
	"MUTE",
	"UNMUTE",
	"PARTY_SILENCE", 
	"PARTY_UNSILENCE",
	"RAID_SILENCE",
	"RAID_UNSILENCE",
	"BATTLEGROUND_SILENCE", 
	"BATTLEGROUND_UNSILENCE",
	"WHISPER", 
	"PROMOTE", 
	"PROMOTE_GUIDE", 
	"LOOT_PROMOTE", 
	"VOTE_TO_KICK",
	"UNINVITE",
	"INSPECT",
	"ACHIEVEMENTS", 
	"TRADE", 
	"FOLLOW", 
	"DUEL", 
	"RAID_TARGET_ICON",
	"SELECT_ROLE", 
	"PVP_REPORT_AFK",
	"RAF_SUMMON", 
	"RAF_GRANT_LEVEL",
	"CANCEL",}
	
UnitPopupMenus["PLAYER"] = {
	"WHISPER",
	"INSPECT", 
	"INVITE",
	"ACHIEVEMENTS",
	"TRADE",
	"FOLLOW",
	"DUEL",
	"RAID_TARGET_ICON", 
	"RAF_SUMMON",
	"RAF_GRANT_LEVEL",
	"CANCEL",}
	
UnitPopupMenus["RAID_PLAYER"] = {
	"MUTE", 
	"UNMUTE",
	"RAID_SILENCE",
	"RAID_UNSILENCE", 
	"BATTLEGROUND_SILENCE", 
	"BATTLEGROUND_UNSILENCE",
	"WHISPER",
	"INSPECT", 
	"ACHIEVEMENTS", 
	"TRADE", 
	"FOLLOW",
	"DUEL",
	"RAID_TARGET_ICON",
	"SELECT_ROLE",
	"RAID_LEADER", 
	"RAID_PROMOTE", 
	"RAID_DEMOTE",
	"LOOT_PROMOTE",
	"RAID_REMOVE", 
	"PVP_REPORT_AFK",
	"RAF_SUMMON", 
	"RAF_GRANT_LEVEL", 
	"CANCEL",}
	
UnitPopupMenus["RAID"] = {
	"MUTE", 
	"UNMUTE", 
	"RAID_SILENCE",
	"RAID_UNSILENCE",
	"BATTLEGROUND_SILENCE",
	"BATTLEGROUND_UNSILENCE",
	"RAID_LEADER", 
	"RAID_PROMOTE",
	"RAID_MAINTANK",
	"RAID_MAINASSIST", 
	"LOOT_PROMOTE", 
	"RAID_DEMOTE", 
	"RAID_REMOVE",
	"PVP_REPORT_AFK",
	"MOVE_PLAYER_FRAME", 
	"MOVE_TARGET_FRAME", 
	"CANCEL",}
	
UnitPopupMenus["VEHICLE"] = {
	"RAID_TARGET_ICON",
	"VEHICLE_LEAVE",
	"CANCEL",}
	
UnitPopupMenus["TARGET"] = {
	"RAID_TARGET_ICON", 
	"CANCEL",}
	
UnitPopupMenus["ARENAENEMY"] = {
	"CANCEL",}

UnitPopupMenus["FOCUS"] = {
	"RAID_TARGET_ICON",
	"CANCEL",}
UnitPopupMenus["BOSS"] = {
	"RAID_TARGET_ICON",
	"CANCEL",}
	